/*
 * Copyright (C) 2014 Freescale Semiconductor, Inc.
 * All rights reserved.
 *
 * This software may be distributed under the terms of the
 * GNU General Public License ("GPL") as published by the Free Software
 * Foundation, either version 2 of that License or (at your option) any
 * later version.
 *
 * THIS SOFTWARE IS PROVIDED BY Freescale Semiconductor ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL Freescale Semiconductor BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef LS_DBG_H
#define LS_DBG_H

enum TRACEIP_MODULE {
	ETM0,
	ETM1,

	ETR,

	ETF0,
	ETF1,

	CSTF0,
	CSTF1,

	EPU,
	GDI,
	CORE,
	NUM_IO_IDS = CORE + 1, /* number of physical reg groups */
	
	VCOUNT = NUM_IO_IDS,  /* ID of virt. regs */

	NUM_IDS = VCOUNT + 1  /* number of total reg groups (virt + phy) */
};

enum RESOURCE_GROUP_ID {
	LSDBG_RES_EPU_COUNTER = 0,
	LSDBG_RES_EPU_GROUP,
	LSDBG_RES_SCU_EVENT,
	LSDBG_RES_GDPESCR
};

#endif  /* LS_DBG_H */
